### PR TITLE
add: missing mdbook plugins

### PR DESCRIPTION
**Pull request by sven-hash**
Feel free to not accept it since you should have something better

### CODE REVIEW

**Comment by mfahampshire** [comment]
thanks for the PR @sven-hash - requested @raphael-walther to have a look at it since he's the one looking after the workflows

**Comment by raphael-walther** [comment]
Thanks @sven-hash

Could you remove the two extra 'v' prefix in the versions ? That works here:
```
cargo install --vers "^0.4" mdbook && cargo install --vers "^0.2.0" mdbook-variables && cargo install --vers "^1.8.0" mdbook-admonish && cargo install --vers "^0.1.2" mdbook-last-changed && cargo install --vers "^0.1.2" mdbook-theme
```

**Comment by sven-hash** [comment]
I don't quite understand, 
You mean removing the `--vers` parameters ? Or correct the version `cargo install --vers "^0.1.2" mdbook-last-changed && cargo install --vers "^0.1.2" mdbook-theme` , `mdbook-last-changed` and `mdbook-theme` have the same version

Feel free to edit the file in the PR, normally you have the rights

**Comment by raphael-walther** [comment]
There was two typo in the version specification that cargo didn't like. I fixed it in the commit. Thanks again for helping.

**Pull request merged**
